events {
}

http {

     server {
	listen 443 ssl;
        server_name beauty;

	ssl_certificate /etc/nginx/selfsigned.crt;
        ssl_certificate_key /etc/nginx/selfsigned.key;
	
	location / {
		root /usr/share/nginx/html;
		index index.html;
	}
     }
}

