version: '3.8'


services:
  game:
    image: sriramk16/gamingzoneprod:35e6473
    ports:
      - "9092:3000"
    depends_on:
      - tictoc

    networks:
      - srinet
    volumes:
      - srivol:/opt/sri

    secrets:
      - gta_codes
    env_file:
      - ./game.env


    deploy:
      replicas: 2
    
      resources:
        limits:
          cpus: '0.35'
          memory: 356M
        reservations:
          cpus: '0.25'
          memory: 256M

      restart_policy:
        condition: any
      
      placement:
        constraints:
          - node.hostname==worker1
  
  tictoc:
    image: sriramk16/tic-tac-toe:latest
    ports:
      - "9094:3000"
    
    networks:
      - ramnet
    volumes:
      - ramvol:/opt/ram
    environment:
      Env: Dev
      Project: Phoenix

    deploy:
      replicas: 2
      placement:
        preferences:
          - spread: node.labels.workers

#- node.labels.workers==tictoc -- This is for choosing nodes with label for constraints

    healthcheck:
      test: ['CMD', 'curl', 'http://172.31.12.29:9092']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

networks:
  srinet:
    driver: overlay
  ramnet:
    driver: overlay

volumes:
  srivol:
  ramvol:

secrets:
  gta_codes:
    file: ./gta_cheat_codes
