events {
}

http {

     upstream loadbalancer {
	#ip_hash;
	least_conn;
	server beauty:443 weight=50;
	server game:443 weight=50;
     }
     server {
     	listen 80;
	return 301 https://$host$request_uri;
     }

     server {
	listen 443 ssl;
	#listen 80;
        
	ssl_certificate /etc/nginx/selfsigned.crt;
        ssl_certificate_key /etc/nginx/selfsigned.key;
	
	location / {
		proxy_pass https://loadbalancer;
		proxy_ssl_verify off;

		# proxy_set_header Host $host;
		#Pass the original hostname to the backend

		# proxy_set_header X-Real-IP $remote_addr;
		#Pass the client's real IP
		
		#proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		#Keep track of the chain of IPs through proxies

		#proxy_set_header X-Forwarded-Proto $scheme;
		#Redirect users based on whether the original request based on HTTP or HTTPS.
	}
     }
}

